version: "2"

services:
  app:
    image: aubm/books-api
    ports:
      - 8080:8080
    env_file:
      - ./common.env
  db:
    image: mysql:5.6
    ports:
      - 3307:3306
    env_file:
      - ./common.env
